djangoproject/urls.py
from django.contrib import admin
from django.urls import path, include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),]

home/urls.py
from django.urls import path

from . import views

app_name = "home"

urlpatterns = [
    path('', views.home, name='home'),
    path('publications', views.publications, name='publications'),
    path('talks', views.talks, name='talks'),
    path('software', views.software, name='software'),
    path('teaching', views.teaching, name='teaching'),
    path('challenges', views.challenges, name='challenges'),
    path('contact', views.contact, name='contact'),

    path('test', views.test, name='test')
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render

def home(request):
    return render(request, 'home/home.html', {})

def publications(request):
    return render(request, 'home/publications.html', {})

def talks(request):
    return render(request, 'home/talks.html', {})

def software(request):
    return render(request, 'home/software.html', {})

def teaching(request):
    return render(request, 'home/teaching.html', {})

def contact(request):
    return render(request, 'home/contact.html', {})

def challenges(request):
    return render(request, 'home/challenges.html', {})

def test(request):
    return render(request, 'home/test.html', {})

home/templates/home/challenges.html
{% extends "base.html" %}

{% load static %}

{% block content %}
<main class="container">
    <div class="columns">
        <div class="column is-one-third">
            <article class="message is-link">
                <div class="message-header">
                    <p>ROADEF Challenge 2012</p>
                </div>
                <div class="message-body">
                    <strong>Rank :</strong> Unranked

                    <br /><br />

                    <strong>Repository :</strong> <a
                        href="https://github.com/AllergicMushroom/RoadefChallenge2012">GitHub</a>
                </div>
            </article>
        </div>
    </div>
</main>
{% endblock %}

home/templates/home/contact.html
{% extends "base.html" %}

{% load static %}

{% block content %}
<main class="container">
    <div style="margin: 40px;">
        <div class="is-size-2">
            Contact
        </div>

        <br />

        <div class="is-size-5">
            If you are contacting me for an industrial or academic collaboration in operations research, please contact
            me through my
            <a href="mailto:luis.lopes-marques@u-bordeaux.fr">
                academic email.
            </a>

            Otherwise, feel free to contact me through my
            <a href="mailto:luismarques@luismarques.me">
                personal email.
            </a>

            <br />

            You can also find me at the office 265 in the
            <a href="https://www.math.u-bordeaux.fr/imb/spip.php">
                Institut de Mathématique de Bordeaux.
            </a>
        </div>
</main>
{% endblock %}

home/templates/home/home.html
{% extends "base.html" %}

{% load static %}

{% block content %}
<main class="container">
    <div style="margin: 40px;">
        <div class="is-hidden-desktop">
            <img style="border-radius: 50%;" src="{% static 'home/luis.jpg' %}">
            <div class="is-size-2">
                Luis Marques
            </div>

            <div class="is-size-5 has-text-grey">
                Ph.D Student at Inria, Bordeaux
            </div>

            <br />
            <br />

            <div class="is-size-3">
                About me
            </div>
            <div class="is-size-5">
                I am a third year Ph.D Student, under the supervision of
                <a href="https://edge.gitlabpages.inria.fr/team-members/clautiaux/">
                    François Clautiaux
                </a>
                and
                <a href="https://edge.gitlabpages.inria.fr/team-members/froger/">
                    Aurélien Froger,
                </a>
                at the
                <a href="https://www.inria.fr/fr/centre-inria-universite-bordeaux">
                    Inria Center of the University of Bordeaux
                </a>
                where I am part of the
                <a href="edge.gitlabpages.inria.fr">
                    EDGE
                </a>
                team.

                I study mixed integer linear programming, with a special interest in arc flow and
                aggregation and disaggregation methods.
            </div>
        </div>

        <div class="is-hidden-mobile" style="display: flex;">
            <img style="width: 200px; border-radius: 50%;" src="{% static 'home/luis.jpg' %}">
            <div style="margin-left: 40px; margin-top: -20px;">
                <div class="is-size-2">
                    Luis Marques
                </div>

                <div class="is-size-5 has-text-grey">
                    Ph.D Student at Inria, Bordeaux
                </div>

                <br />
                <br />

                <div class="is-size-3">
                    About me
                </div>
                <div class="is-size-5">
                    I am a third year Ph.D Student, under the supervision of
                    <a href="https://edge.gitlabpages.inria.fr/team-members/clautiaux/">
                        François Clautiaux
                    </a>
                    and
                    <a href="https://edge.gitlabpages.inria.fr/team-members/froger/">
                        Aurélien Froger,
                    </a>
                    at the
                    <a href="https://www.inria.fr/fr/centre-inria-universite-bordeaux">
                        Inria Center of the University of Bordeaux
                    </a>
                    where I am part of the
                    <a href="edge.gitlabpages.inria.fr">
                        EDGE
                    </a>
                    team.

                    I study mixed integer linear programming, with a special interest in arc flow and
                    aggregation and disaggregation methods.
                </div>
            </div>
        </div>

        <br />

        <div class="is-size-3">
            My background
        </div>
        <div class="is-size-5">
            I studied under the
            <a href="https://uf-mi.u-bordeaux.fr/optim/">
                CMI OPTIM
            </a>
            program, a bachelor's and master's degree joint formation under the
            <a href="https://uf-mi.u-bordeaux.fr/mas/">
                Applied Mathematics and Statistics master.
            </a>

            The program explores many aspects of operations research, with a main focus on combinatorial
            optimization.
            During the formation, I had the chance to go abroad for a semester in Odense, Denmark.
            In the last two years, I did two internships, one at
            <a href="https://atoptima.fr/">
                AtOptima,
            </a>
            in Bordeaux, where I worked on a travel time prediction module using machine learning techniques, and
            another
            at
            <a href="https://www.edf.fr/">
                EDF,
            </a>
            in Paris, where I worked on the outage planning of nuclear plants using an arc flow formulation and
            taking
            into account an objective function closer to the true industrial objective.
        </div>

        <br />

        <div class="is-size-3">
            Industrial collaborations
        </div>
        <div class="is-size-5">
            Stay tuned for future updates !
        </div>

        <br />

        <div class="is-size-3">
            Scientific services
        </div>
        <div class="is-size-5">
            <ul>
                <li>
                    In October 2024, I animated a serious-game of the traveling salesman problem for children starting from 6 years old at the <a href="https://sciences-et-technologies.u-bordeaux.fr/actualites/festival-data-party">Data Party</a> festival in Bordeaux, France.
                    During the first day of the festival we had classes of children to whom we introduced the concept of algorithms and how they can be used to solve problems.
                    During the second day, we had a stand where people of any age could come and play the game.
                </li>
            </ul>
        </div>
    </div>
</main>
{% endblock %}

home/templates/home/publications.html
{% extends "base.html" %}

{% load static %}

{% block content %}
<main class="container">
    <div style="margin: 40px;">
        <div class="is-size-2">
            Publications
        </div>

        <br />

        <div class="is-size-5">
            <a href="https://inria.hal.science/hal-04303041">
                <strong>
                    Mathematical models based on decision hypergraphs for designing a storage cabinet
                </strong>
            </a>


            <a href="https://gitlab.inria.fr/edge/scpd/scpd-artifacts" class="button is-primary is-small is-rounded"
                style="margin-left: 8px;">
                Artifacts
            </a>

            <a class="button is-danger is-small is-rounded" disabled>
                Source code
            </a>
        </div>
        <div class="is-size-7 has-text-grey">
            Luis Marques, François Clautiaux, Aurélien Froger
        </div>
        <div class="is-size-7 has-text-grey">
            Preprint submitted on November 2023, accepted on September 2024
        </div>
    </div>
</main>
{% endblock %}

home/templates/home/software.html
{% extends "base.html" %}

{% load static %}

{% block content %}
<main class="container">
    <div style="margin: 40px;">
        <div class="is-size-2">
            Software
        </div>

        <br />

        <div class="is-size-5">
            Stay tuned for future updates !
        </div>
    </div>
</main>
{% endblock %}

home/templates/home/talks.html
{% extends "base.html" %}

{% load static %}

{% block content %}
<main class="container">
    <div style="margin: 40px;">
        <div class="is-size-2">
            Talks and presentations
        </div>

        <br />

        <div class="is-size-5">
            <a href="{% static 'talks/ISMP-072024.pdf' %}">
                <strong>
                    Dynamic programming based arc-flow formulations for cutting and packing problems
                </strong>
            </a>
        </div>
        <div class="is-size-7 has-text-grey">
            <a href="https://ismp2024.gerad.ca/">
                ISMP 2024 in July 2024, Montreal, Canada
            </a>
        </div>
        <div class="is-size-6">
            We study arc-flow formulations obtained from transition graphs or transition hypergraphs of dynamic programs.
    These formulations are known for their generally strong linear relaxations and can be solved directly by a general purpose mixed integer linear programming (MILP) solver.
    An advantage of the MILP formulation is that one can include additional linear constraints in the form of resource constraints.
    In the absence of these, arc-flow formulations in graphs -- resp. hypergraphs -- form a totally unimodular -- resp. totally dual integral -- system, meaning the solution of the linear relaxation of the formulation is integer.
    A drawback of the MILP formulation is its size which can be pseudo-polynomial or exponential.
    We focus on cutting and packing problems with temporal constraints, i.e., temporal knapsack problem, temporal bin packing problem and their variants.
    We introduce preprocessing techniques and dominance rules to reduce the size of the transition graphs and hypergraphs: symmetries reduction, equivalent states aggregation using methods from the literature and detection of states that can be replaced by other states where some constraints are relaxed.
    Numerically, we confirm the strength of the linear relaxation of the arc-flow formulations, we observe that the sizes of the arc-flow formulations are significantly reduced by our techniques and show that these formulations are competitive and can outperform popular compact formulations from the literature.
        </div>

        <br />

        <div class="is-size-5">
            <a href="{% static 'talks/JPOC-062023.pdf' %}">
                <strong>
                    An hypergraph based formulation for an Automatic Storage Design problem
                </strong>
            </a>
        </div>
        <div class="is-size-7 has-text-grey">
            <a href="https://jpoc13.sciencesconf.org/">
                JPOC'13 in June 2023, Clermont-Ferrand, France
            </a>
        </div>
        <div class="is-size-6">
            Due to its length, the abstract is available upon request.
        </div>

        <br />

        <div class="is-size-5">
            <a href="{% static 'talks/ESICUP-052023.pdf' %}">
                <strong>
                    Automatic Storage Design
                </strong>
            </a>
        </div>
        <div class="is-size-7 has-text-grey">
            <a href="https://www.euro-online.org/websites/esicup/19th-esicup-meeting/">
                19th ESICUP Meeting in May 2023, Bologna, Italy
            </a>
        </div>
        <div class="is-size-6">
            Automated storage and retrieval systems have been studied for years in the context of warehouse
            optimization.
            The number
            of shelves and their height is generally determined in such a way that the number of retrieval operations
            per
            minute is
            maximized, i.e., response time is often more important than the space used by the device. In our specific
            study,
            we
            consider the case where capacity is highly constrained, and the efficiency of the system is not an issue. We
            call our
            problem the \emph{Automatic Storage Design} (ASD) problem.

            In the ASD problem, the goal is to design a set of shelves in a box, design a set of compartments in every
            shelf
            and
            assign items to the compartments, where deciding to assign an item is associated with a profit. The
            objective is
            to
            maximize the total profit. The design parts are defined on a set of packing constraints, i.e., the sum of
            the
            shelves'
            heights must not exceed the box's height and the sum of compartments' widths in every shelf must not exceed
            the
            box's
            width. The assignment part is defined on a set of temporal knapsack constraints, i.e., the items must fit
            with
            respect
            to their height, width, length and time windows. For an item to be a candidate for assignment in a
            compartment,
            its
            height must be less than or equal to the compartment's height and its width must be equal to the
            compartment's
            width.
            The length dimension represents the knapsack constraint, i.e., the sum of items' lengths with respect to
            their
            time
            windows must not exceed the compartment's length. This problem generalizes the temporal knapsack problem,
            and
            the
            three-dimensional three-stage guillotine cutting problem.

            We consider several formulations based on integer linear programming (ILP) and dynamic programming. We
            present a
            compact
            ILP formulation serving as a reference point. We formulate the ASD problem as a dynamic program with
            additional
            constraints and show that it is equivalent to the search for a max-cost flow in an directed acyclic
            hypergraph.
            From
            this representation, we derive an ILP flow-model and a label setting algorithm. In order for our methods to
            be
            as
            competitive as possible, we introduce several preprocessing procedures to reduce the size of the hypergraph.

            Extensive numerical studies are performed on a set of 320 randomly generated instances to assess the
            efficiency
            of our
            methods and compare them with each other.
            We also evaluate the impact of the design and the temporal knapsack aspect of the problem on the results.
        </div>

        <br />

        <div class="is-size-5">
            <a href="{% static 'talks/IMB-042023.pdf' %}">
                <strong>
                    Automatic Storage Design
                </strong>
            </a>
        </div>
        <div class="is-size-7 has-text-grey">
            <a href="https://edge.gitlabpages.inria.fr/projects/adlib/">
                ADLib seminar in April 2023, Bordeaux, France
            </a>
        </div>
        <div class="is-size-6">
            No abstract available.
        </div>
    </div>
</main>
{% endblock %}

home/templates/home/teaching.html
{% extends "base.html" %}

{% load static %}

{% block content %}
<main class="container">
    <div style="margin: 40px;">
        <div class="is-size-2">
            Teaching
        </div>

        <br />

        <div class="is-size-5">
            <a href="https://formations.u-bordeaux.fr/#/details-formation?type=enseignement&id=38859">
                <strong>
                    4TMQ407U - Programming for scientific computing
                </strong>
            </a>
        </div>
        <div class="is-size-7 has-text-grey">
            34 hours in 2025
        </div>
        <div class="is-size-6">
            The goal of this course is to introduce second-year students to the C++ programming language.
            The concepts studied go from the most basic concepts to loops, functions, arrays, structured types and
            interaction with the user.
            Compilation and debugging mechanisms are also explained.
        </div>

        <br />

        <div class="is-size-5">
            <a href="https://formations.u-bordeaux.fr/#/details-formation?type=enseignement&id=38859">
                <strong>
                    4TMQ407U - Programming for scientific computing
                </strong>
            </a>
        </div>
        <div class="is-size-7 has-text-grey">
            34 hours in 2024
        </div>
        <div class="is-size-6">
            The goal of this course is to introduce second-year students to the C++ programming language.
            The concepts studied go from the most basic concepts to loops, functions, arrays, structured types and
            interaction with the user.
            Compilation and debugging mechanisms are also explained.
        </div>

        <br />

        <div class="is-size-5">
            <a href="https://formations.u-bordeaux.fr/#/details-formation?type=enseignement&id=40687">
                <strong>
                    4TOP101U - Domains of optimization
                </strong>
            </a>
        </div>
        <div class=" is-size-7 has-text-grey">
            3 hours in 2023
        </div>
        <div class="is-size-6">
            The goal of this course is to introduce first-year students to operations research using a popularization
            methodology. Divided in groups, the students present a subject related to operations research using a
            methodology such that
            people exterior to the domain can understand.
        </div>

        <br />

        <div class="is-size-5">
            <a href="https://formations.u-bordeaux.fr/#/details-formation?type=enseignement&id=55066">
                <strong>
                    4TMS027U - Constraint programming
                </strong>
            </a>
        </div>
        <div class="is-size-7 has-text-grey">
            15 hours in 2023
        </div>
        <div class="is-size-6">
            The goal of this course is to introduce fifth-year students to the basic concepts of constraint
            programming, a paradigm
            different from linear programming.
            Global constraints are introduced and domain filtering techniques relying on those contraints are
            explored.
            The course is based on the commercial solver
            <a href="https://www.ibm.com/docs/fr/icos/22.1.1?topic=manual-opl-modeling-language">
                OPL
            </a>.
        </div>

        <br />

        <div class="is-size-5">
            <a href="https://formations.u-bordeaux.fr/#/details-formation?type=enseignement&id=38859">
                <strong>
                    4TMQ407U - Programming for scientific computing
                </strong>
            </a>
        </div>
        <div class="is-size-7 has-text-grey">
            34 hours in 2023
        </div>
        <div class="is-size-6">
            The goal of this course is to introduce second-year students to the C++ programming language.
            The concepts studied go from the most basic concepts to loops, functions, arrays, structured types and
            interaction with the user.
            Compilation and debugging mechanisms are also explained.
        </div>
    </div>
</main>
{% endblock %}

home/templates/home/test.html
{% load static %}

<!DOCTYPE html>
<html lang="fr" class="has-background-light">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta name="author" content="Luis Marques" />
    <meta name="keywords" content="Luis Marques" />

    <link rel="stylesheet" type="text/css" href="{% static 'CSS/bulma.css' %}" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">

    <!-- <script src="{% static 'Scripts/bulma.js' %}"></script> -->

    <title>Luis Marques</title>
    <link rel="icon" href="{% static 'Assets/Icons/Icon.ico' %}">
</head>

<body class="has-navbar-fixed-top">

    <nav class="navbar" role="navigation" aria-label="main navigation">
        <div class="navbar-brand">
            <a class="navbar-item" href="https://bulma.io">
                <img src="https://bulma.io/images/bulma-logo.png"
                    alt="Bulma: Free, open source, and modern CSS framework based on Flexbox" width="112" height="28">
            </a>

            <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false">
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
            </a>
        </div>
    </nav>

</body>

{% block script %}
{% endblock %}

</html>

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="fr" class="has-background-light">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta name="author" content="Luis Marques" />
    <meta name="keywords" content="Luis Marques" />

    <link rel="stylesheet" type="text/css" href="{% static 'CSS/bulma.css' %}" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">

    <script>
        document.addEventListener('DOMContentLoaded', () => {

            // Get all "navbar-burger" elements
            const $navbarBurgers = Array.prototype.slice.call(document.querySelectorAll('.navbar-burger'), 0);

            // Add a click event on each of them
            $navbarBurgers.forEach(el => {
                el.addEventListener('click', () => {

                    // Get the target from the "data-target" attribute
                    const target = el.dataset.target;
                    const $target = document.getElementById(target);

                    // Toggle the "is-active" class on both the "navbar-burger" and the "navbar-menu"
                    el.classList.toggle('is-active');
                    $target.classList.toggle('is-active');

                });
            });

        });
    </script>

    <title>Luis Marques</title>
    <link rel="icon" href="{% static 'Assets/Icons/Icon.ico' %}">
</head>

<body class="has-navbar-fixed-top">
    <!-- ! Mobile navbar -->
    <nav class="navbar is-hidden-desktop is-fixed-top" role="navigation" aria-label="main navigation">
        <div class="navbar-brand">
            <a class="navbar-item" href="/">
                Luis Marques
            </a>

            <div role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navMenu">
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
            </div>
        </div>

        <div id="navMenu" class="navbar-menu">
            <div class="navbar-start">
                <a class="navbar-item" href="{% url 'home:publications' %}">
                    <span>
                        Publications
                    </span>
                </a>

                <a class="navbar-item" href="{% url 'home:talks' %}">
                    <span>
                        Talks
                    </span>
                </a>

                <a class="navbar-item" href="{% url 'home:software' %}">
                    <span>
                        Software
                    </span>
                </a>

                <a class="navbar-item" href="{% url 'home:teaching' %}">
                    <span>
                        Teaching
                    </span>
                </a>

                <!-- <a class="navbar-item" href="{% url 'home:challenges' %}">
                    <span>
                        Challenges
                    </span>
                </a> -->

                <a class="navbar-item" href="{% url 'home:contact' %}">
                    <span>
                        Contact
                    </span>
                </a>
            </div>
        </div>
    </nav>

    <!-- ! Desktop navbar -->
    <nav class="navbar is-hidden-mobile is-hidden-tablet-only is-fixed-top" role="navigation"
        aria-label="main navigation">
        <div class="navbar-brand is-size-4" style="margin-left: 24rem">
            <a class="navbar-item" href="/">
                <span>
                    <b>
                        Luis Marques
                    </b>
                </span>
            </a>
        </div>

        <div class="navbar-menu">
            <div class="navbar-end" style="margin-right: 24rem">

                <a class="navbar-item" href="{% url 'home:publications' %}">
                    <span>
                        Publications
                    </span>
                </a>

                <a class="navbar-item" href="{% url 'home:talks' %}">
                    <span>
                        Talks
                    </span>
                </a>

                <a class="navbar-item" href="{% url 'home:software' %}">
                    <span>
                        Software
                    </span>
                </a>

                <a class="navbar-item" href="{% url 'home:teaching' %}">
                    <span>
                        Teaching
                    </span>
                </a>

                <!-- <a class="navbar-item" href="{% url 'home:challenges' %}">
                    <span>
                        Challenges
                    </span>
                </a> -->

                <a class="navbar-item" href="{% url 'home:contact' %}">
                    <span>
                        Contact
                    </span>
                </a>
            </div>
        </div>
    </nav>

    <div class="column is-fullheight">
        <!-- Beginning of content block div-->
        {% block content %}
        {% endblock %}
    </div><!-- End of content block div-->

</body>

{% block script %}
{% endblock %}

</html>